# Generated by Django 5.0.6 on 2024-07-13 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0002_todolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='user_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='List.userdetails'),
        ),
    ]
