# Generated by Django 5.0.1 on 2024-10-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0006_alter_posts_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
